platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'EmplesMVVMReactiveCocoa' do
    pod 'ReactiveCocoa'
    pod 'Swinject'
    pod 'ObjectMapper', '~> 3.0.0'
    pod 'Kingfisher', '~>4.2.0'
    pod 'GoogleMaps'
    pod 'iCarousel'
    pod 'Koloda'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'ReactiveCocoa'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end

end
