platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'emplesMVC' do
    pod 'FieryCrucible'
    pod 'ObjectMapper', '~> 3.0.0'
    pod 'Kingfisher', '~>4.2.0'
    pod 'GoogleMaps'
    pod 'iCarousel'
    pod 'Koloda'
    pod 'SwiftLint'    
    
    abstract_target 'Tests' do
        target "emplesMVCTests"
        
        pod 'Quick'
        pod 'Nimble'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
            config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
        end
    end
end

